### ISSUE TITLE
KeyError: 128

### ISSUE THREAD

**Issue by jguionnet** [run-llama/llama_docs_bot#2]
I tried to run it
#!/usr/bin/env bash -v
set -o errexit
set -o nounset
set -o pipefail

# assumes you have virtualenv installed and you created a virtualenv named .venv
if [ ! -d ".venv" ]; then
    python3.11 -m venv ".venv"
    source .venv/bin/activate
    pip install -r requirements.txt
fi

source .venv/bin/activate
cd llama_docs_bot
python3 app.py

and got this error (after changing 
from .markdown_docs_reader import MarkdownDocsReader
to
from markdown_docs_reader import MarkdownDocsReader

Traceback (most recent call last):
  File "/Users/jguionnet/workspace/llama_docs_bot/llama_docs_bot/indexing.py", line 57, in get_query_engine_tool
    storage_context = StorageContext.from_defaults(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/storage/storage_context.py", line 75, in from_defaults
    docstore = docstore or SimpleDocumentStore.from_persist_dir(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/storage/docstore/simple_docstore.py", line 57, in from_persist_dir
    return cls.from_persist_path(persist_path, namespace=namespace, fs=fs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/storage/docstore/simple_docstore.py", line 75, in from_persist_path
    simple_kvstore = SimpleKVStore.from_persist_path(persist_path, fs=fs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/storage/kvstore/simple_kvstore.py", line 75, in from_persist_path
    with fs.open(persist_path, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/fsspec/spec.py", line 1309, in open
    f = self._open(
        ^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/fsspec/implementations/local.py", line 180, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/fsspec/implementations/local.py", line 298, in __init__
    self._open()
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/fsspec/implementations/local.py", line 303, in _open
    self.f = open(self.path, mode=self.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jguionnet/workspace/llama_docs_bot/llama_docs_bot/data_community/docstore.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jguionnet/workspace/llama_docs_bot/llama_docs_bot/app.py", line 29, in <module>
    query_engine_tools = [
                         ^
  File "/Users/jguionnet/workspace/llama_docs_bot/llama_docs_bot/app.py", line 30, in <listcomp>
    get_query_engine_tool(directory, description) for directory, description in docs_directories.items()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/llama_docs_bot/indexing.py", line 67, in get_query_engine_tool
    nodes, leaf_nodes = load_markdown_docs(directory)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/llama_docs_bot/indexing.py", line 51, in load_markdown_docs
    nodes = node_parser.get_nodes_from_documents(documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/node_parser/hierarchical.py", line 210, in get_nodes_from_documents
    nodes_from_doc = self._recursively_get_nodes_from_nodes([doc], 0)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/node_parser/hierarchical.py", line 178, in _recursively_get_nodes_from_nodes
    sub_sub_nodes = self._recursively_get_nodes_from_nodes(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/node_parser/hierarchical.py", line 178, in _recursively_get_nodes_from_nodes
    sub_sub_nodes = self._recursively_get_nodes_from_nodes(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jguionnet/workspace/llama_docs_bot/.venv/lib/python3.11/site-packages/llama_index/node_parser/hierarchical.py", line 159, in _recursively_get_nodes_from_nodes
    self.text_splitter_map[self.text_splitter_ids[level]],
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '128'

**Comment by logan-markewich** [comment]
@jguionnet Yea mb, made a fix for this in the demo that I forgot to commit to the llama-index lib

Quick Fix while I get that merged:

```
node_parser = HierarchicalNodeParser.from_defaults(
    chunk_sizes=[
        large_chunk_size, 
        large_chunk_size // 3,
    ],
    text_splitter_ids=[
        large_chunk_size, 
        large_chunk_size // 3,
    ],
)
```

**Comment by Sheldongg** [comment]
when i run the 5_retrival.ipynd also meet the same issue, and I have updated llama-index to the latest version.

and I tried to modify the node_parser variable in the load_markdown_docs function as follows:

Original code:

`node_parser = HierarchicalNodeParser.from_defaults(
    chunk_sizes=[large_chunk_size, large_chunk_size // 3]
)`
 
Modified code:

`node_parser = HierarchicalNodeParser.from_defaults(
    chunk_sizes=[large_chunk_size, large_chunk_size // 3],
    text_splitter_ids=[large_chunk_size, large_chunk_size // 3]
)`
 
However, it did not work and caused other errors.'



`FileNotFoundError                         Traceback (most recent call last)
Cell In[13], line 10, in get_query_engine_tool(directory, description, hierarchical, postprocessors)
      9 try:
---> 10     storage_context = StorageContext.from_defaults(
     11         persist_dir=f"./data_{os.path.basename(directory)}"
     12     )
     13     index = load_index_from_storage(storage_context)

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/storage/storage_context.py:75, in StorageContext.from_defaults(cls, docstore, index_store, vector_store, graph_store, persist_dir, fs)
     74 else:
---> 75     docstore = docstore or SimpleDocumentStore.from_persist_dir(
     76         persist_dir, fs=fs
     77     )
     78     index_store = index_store or SimpleIndexStore.from_persist_dir(
     79         persist_dir, fs=fs
     80     )

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/storage/docstore/simple_docstore.py:57, in SimpleDocumentStore.from_persist_dir(cls, persist_dir, namespace, fs)
     56     persist_path = os.path.join(persist_dir, DEFAULT_PERSIST_FNAME)
---> 57 return cls.from_persist_path(persist_path, namespace=namespace, fs=fs)

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/storage/docstore/simple_docstore.py:75, in SimpleDocumentStore.from_persist_path(cls, persist_path, namespace, fs)
     66 """Create a SimpleDocumentStore from a persist path.
     67 
     68 Args:
   (...)
     72 
     73 """
---> 75 simple_kvstore = SimpleKVStore.from_persist_path(persist_path, fs=fs)
     76 return cls(simple_kvstore, namespace)

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/storage/kvstore/simple_kvstore.py:75, in SimpleKVStore.from_persist_path(cls, persist_path, fs)
     74 logger.debug(f"Loading {__name__} from {persist_path}.")
---> 75 with fs.open(persist_path, "rb") as f:
     76     data = json.load(f)

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/fsspec/spec.py:1241, in AbstractFileSystem.open(self, path, mode, block_size, cache_options, compression, **kwargs)
   1240 ac = kwargs.pop("autocommit", not self._intrans)
-> 1241 f = self._open(
   1242     path,
   1243     mode=mode,
   1244     block_size=block_size,
   1245     autocommit=ac,
   1246     cache_options=cache_options,
   1247     **kwargs,
   1248 )
   1249 if compression is not None:

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/fsspec/implementations/local.py:184, in LocalFileSystem._open(self, path, mode, block_size, **kwargs)
    183     self.makedirs(self._parent(path), exist_ok=True)
--> 184 return LocalFileOpener(path, mode, fs=self, **kwargs)

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/fsspec/implementations/local.py:315, in LocalFileOpener.__init__(self, path, mode, autocommit, fs, compression, **kwargs)
    314 self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 315 self._open()

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/fsspec/implementations/local.py:320, in LocalFileOpener._open(self)
    319 if self.autocommit or "w" not in self.mode:
--> 320     self.f = open(self.path, mode=self.mode)
    321     if self.compression:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/lidong/project/llamaindex/llama_docs_bot/5_retrieval/data_query_modules/docstore.json'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
Cell In[14], line 1
----> 1 hierarchical_engine = get_query_engine_tool(
      2     "/Users/lidong/project/llamaindex/llama_docs_bot/docs/core_modules/query_modules",
      3     "Useful for information on various query engines and retrievers, and anything related to querying data.",
      4     hierarchical=True, 
      5 ).query_engine

Cell In[13], line 24, in get_query_engine_tool(directory, description, hierarchical, postprocessors)
     22 except:
     23     if hierarchical:
---> 24         nodes, leaf_nodes = load_markdown_docs(directory, hierarchical=hierarchical)
     26         docstore = SimpleDocumentStore()
     27         docstore.add_documents(nodes)

Cell In[12], line 48, in load_markdown_docs(filepath, hierarchical)
     31     # node_parser = HierarchicalNodeParser.from_defaults(
     32     #     chunk_sizes=[
     33     #         large_chunk_size, 
   (...)
     39     #     ]
     40     # )
     41     node_parser = HierarchicalNodeParser.from_defaults(
     42         chunk_sizes=[
     43             large_chunk_size, 
     44             large_chunk_size // 3,
     45         ]
     46     )
---> 48     nodes = node_parser.get_nodes_from_documents(documents)
     49     return nodes, get_leaf_nodes(nodes)
     50 else:

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/node_parser/hierarchical.py:210, in HierarchicalNodeParser.get_nodes_from_documents(self, documents, show_progress)
    208 # TODO: a bit of a hack rn for tqdm
    209 for doc in documents_with_progress:
--> 210     nodes_from_doc = self._recursively_get_nodes_from_nodes([doc], 0)
    211     all_nodes.extend(nodes_from_doc)
    213 if self.metadata_extractor is not None:

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/node_parser/hierarchical.py:178, in HierarchicalNodeParser._recursively_get_nodes_from_nodes(self, nodes, level, show_progress)
    176 # now for each sub-node, recursively split into sub-sub-nodes, and add
    177 if level < len(self.text_splitter_ids) - 1:
--> 178     sub_sub_nodes = self._recursively_get_nodes_from_nodes(
    179         sub_nodes,
    180         level + 1,
    181         show_progress=show_progress,
    182     )
    183 else:
    184     sub_sub_nodes = []

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/node_parser/hierarchical.py:178, in HierarchicalNodeParser._recursively_get_nodes_from_nodes(self, nodes, level, show_progress)
    176 # now for each sub-node, recursively split into sub-sub-nodes, and add
    177 if level < len(self.text_splitter_ids) - 1:
--> 178     sub_sub_nodes = self._recursively_get_nodes_from_nodes(
    179         sub_nodes,
    180         level + 1,
    181         show_progress=show_progress,
    182     )
    183 else:
    184     sub_sub_nodes = []

File ~/anaconda3/envs/chatdoc/lib/python3.10/site-packages/llama_index/node_parser/hierarchical.py:159, in HierarchicalNodeParser._recursively_get_nodes_from_nodes(self, nodes, level, show_progress)
    155 sub_nodes = []
    156 for node in nodes_with_progress:
    157     cur_sub_nodes = get_nodes_from_document(
    158         node,
--> 159         self.text_splitter_map[self.text_splitter_ids[level]],
    160         self.include_metadata,
    161         include_prev_next_rel=self.include_prev_next_rel,
    162     )
    163     # add parent relationship from sub node to parent node
    164     # add child relationship from parent node to sub node
    165     # NOTE: Only add relationships if level > 0, since we don't want to add
    166     # relationships for the top-level document objects that we are splitting
    167     if level > 0:

KeyError: '128'`
